#!/bin/bash
COMPILER=${DCOMPILER:=dmd}
VERSION=${DVERSION:=latest}
TOOL=${DTOOL:=${COMPILER}}

if [ "${TOOL}" = "ldc" ]; then
  TOOL='ldc2'
fi

if [ -n "${verbose}" ]; then
  echo "Compiler ${COMPILER} in Version ${VERSION} using ${TOOL}"
fi

if [ -n "${USE_LOCAL_USER}" ]; then
  OPTIONS="-e USER -e HOME -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_GROUP_ID=`id -g $USER`"
fi
if [ -n "${FORCE_PULL}" ]; then
  docker pull dlanguage/${COMPILER}:${VERSION}
fi
docker run --rm -ti ${OPTIONS:=} -w /user -v $(pwd):/user dlanguage/${COMPILER}:${VERSION} ${TOOL} $@
