#!/bin/bash
COMPILER=${DCOMPILER:=dmd}
VERSION=${DVERSION:=latest}
TOOL=${DTOOL:=${COMPILER}}

if [ "${TOOL}" = "ldc" ]
then
  TOOL='ldc2'
fi

if [ -n "${verbose}" ]
then
  echo "Compiler ${COMPILER} in Version ${VERSION} using ${TOOL}"
fi

#  -e USER -e HOME -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_GROUP_ID=`id -g $USER` \
docker run --rm -ti \
  -w /user \
  -v $(pwd):/user \
  dlanguage/${COMPILER}:${VERSION} ${TOOL} $@
