#!/bin/bash

function test() {
  docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/$1 | grep -q "^Hello World.*$"
  if [ $? -ne 0 ]; then
    echo "Failed"
    exit 1
  fi
  echo 'ok'
}

function compile() {
  echo -n "Compiling Hello World using $1 ... "
  DCOMPILER=$1 ./compile $2 hello_world/hello_world.d
}

compile 'dmd' '-ofhello_world.dmd' &&
test 'hello_world.dmd'

compile 'gdc' '-o hello_world.gdc' &&
test 'hello_world.gdc'

compile 'ldc' '-ofhello_world.ldc' &&
test 'hello_world.ldc'
