#!/bin/bash

function test() {
  docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/$1
  if [ $? -ne 23 ]; then
    echo "Failed"
    exit 1
  fi
  echo 'ok'
}

function compile() {
  echo -n "Compiling Return Code Example using $1 ... "
  DCOMPILER=$1 ./compile $2 return_code/return_code.d
}

compile 'dmd' '-ofreturn_code.dmd' &&
test 'return_code.dmd'

compile 'gdc' '-o return_code.gdc' &&
test 'return_code.gdc'

compile 'ldc' '-ofreturn_code.ldc' &&
test 'return_code.ldc'

compile 'sdc' '-o return_code.sdc' &&
test 'return_code.sdc'
